trigger:
  batch: true
  branches:
    include:
      - "*"

pr: none

workspace:
    clean: all

variables:
  buildConfiguration: 'release'
  buildPlatform: 'anycpu'

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/heads/master
    endpoint: "GitHub (SFA)"

pool:
  name: 'DAS - Continuous Integration'
  demands: 
  - gulp

steps:
- task: gittools.gitversion-preview.gitversion-task.GitVersion@5
  displayName: GitVersion

- task: Npm@1
  displayName: 'npm install'

- task: gulp@1
  inputs:
    gulpfile: 'gulpfile.js'
    targets: build

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    contents: |
     dist/**
     azure/**
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  
- template: azure-pipelines-templates/dependency-check.yml@das-platform-building-blocks

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
