trigger:
  batch: true
  branches:
    include:
      - "master"

workspace:
    clean: all

variables:
  buildConfiguration: 'release'
  buildPlatform: 'anycpu'

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.4.61
    endpoint: SkillsFundingAgency

pool:
  name: 'DAS - Continuous Integration Agents'
  demands: 
  - gulp
  - LATEST_DOTNET_VERSION -equals 3.1

steps:
- template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks

- task: Npm@1
  displayName: 'npm install'

- task: gulp@1
  inputs:
    gulpfile: 'gulpfile.js'
    targets: build

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    contents: |
     dist/**
     azure/**
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
